language: go
go_import_path: github.com/andyzhangx/azuredisk-csi-driver

env:
  global:
    - GO111MODULE=off

go:
  - "1.10.x"
  - "1.11.4"

script:
  - |
    set -e
    # fail loudly when force-pushed
    MODIFIED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
    # waiting for native solution https://github.com/travis-ci/travis-ci/issues/6301
    if ! echo ${MODIFIED_FILES} | grep -qvE '(\.md$)|(^doc)/'; then
      echo "Only docs were updated, stopping build process."
      exit 0
    fi
  - hack/verify-all.sh
  - make test
  - make azuredisk
  - make azuredisk-windows
  - make azuredisk-container
