language: go
go_import_path: github.com/andyzhangx/azuredisk-csi-driver

env:
  global:
    - GO111MODULE=off

go:
  - "1.10.x"
  - "1.11.4"

script:
  - hack/verify-all.sh
  - make test
  - make azuredisk
  - make azuredisk-container
