language: go
go_import_path: github.com/kubernetes-sigs/azuredisk-csi-driver
dist: bionic

env:
  global:
    - GO111MODULE=off

go:
  - "1.12.1"

jobs:
  include:
    - stage: test
      name: "code verification test"
      install:
        - go get github.com/mattn/goveralls
        - go get github.com/golang/dep/cmd/dep
      script:
        - make verify
    - stage: test
      name: "unit test"
      install:
        - GO111MODULE=off go get github.com/mattn/goveralls
      script:
        - make unit-test
    - stage: test
      name: "sanity test"
      script:
        - make sanity-test
    - stage: test
      name: "integration test"
      install:
        - go get github.com/rexray/gocsi/csc
        - sudo apt update && sudo apt install procps -y  # for installing pkill
      script:
        - make integration-test
