language: go
go_import_path: github.com/kubernetes-sigs/azuredisk-csi-driver
dist: bionic

env:
  global:
    - GO111MODULE=off

go:
  - "1.12.1"

jobs:
  include:
    - stage: test
      name: "build test"
      install:
        - GO111MODULE=off go get github.com/mattn/goveralls
        - go get github.com/golang/dep/cmd/dep
      script:
        - hack/verify-all.sh
        - make azuredisk
        - make azuredisk-container
        - make azuredisk-windows
        - go test -covermode=count -coverprofile=profile.cov ./pkg/...
    - stage: test
      name: "sanity test"
      script: 
        - make azuredisk
        - make sanity-test
    - stage: test
      name: "integration test"
      install:
        - GO111MODULE=off go get github.com/rexray/gocsi/csc
        - sudo apt update && sudo apt install procps -y  # for installing pkill
      script:
        - make azuredisk
        - make integration-test
