kind: Pod
apiVersion: v1
metadata:
  name: nginx-azuredisk
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux
  containers:
  - image: nginx
    name: nginx-azuredisk
    command:
    - "/bin/sh"
    - "-c"
    - while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 1; done
    volumeDevices:
    - name: azuredisk01
      devicePath: /dev/xvda
  volumes:
  - name: azuredisk01
    persistentVolumeClaim:
      claimName: pvc-azuredisk
