apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk-cloning
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: disk.csi.azure.com
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-azuredisk
