image:
  azuredisk:
    repository: mcr.microsoft.com/k8s/csi/azuredisk-csi
    tag: latest
    pullPolicy: IfNotPresent
  csiProvisioner:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner
    tag: v1.5.0
    pullPolicy: IfNotPresent
  csiAttacher:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-attacher
    tag: v1.2.0
    pullPolicy: IfNotPresent
  clusterDriverRegistrar:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-cluster-driver-registrar
    tag: v1.0.1
    pullPolicy: IfNotPresent
  csiSnapshotter:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-snapshotter
    tag: v2.0.0
    pullPolicy: IfNotPresent
  csiResizer:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-resizer
    tag: v0.3.0
    pullPolicy: IfNotPresent
  livenessProbe:
    repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
    tag: v1.1.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
    tag: v1.2.0
    pullPolicy: IfNotPresent
  csiSnapshotController:
    repository: mcr.microsoft.com/oss/kubernetes-csi/snapshot-controller
    tag: v2.0.0
    pullPolicy: IfNotPresent

serviceAccount:
  create: true

rbac:
  create: true

controller:
  replicas: 2

node:
  metricsPort: 29605

snapshotController:
  replicas: 1
