---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-restored
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - image: nginx
      name: nginx-restored
      args:
        - sleep
        - "3600"
      volumeMounts:
        - name: azuredisk01
          mountPath: "/mnt/azuredisk"
  volumes:
    - name: azuredisk01
      persistentVolumeClaim:
        claimName: pvc-azuredisk-snapshot-restored
